markdown: kramdown
permalink: /:year/:month/:day/:title/
url: http://acayf.github.io
author: aCayF
highlighter: rouge 
exclude: ["Rakefile", "CNAME", "README.md"]
safe: false
paginate: 15


# Gems
gems: [jekyll-paginate]
